### ISSUE TITLE
Server Error in '/' Application :(

### ISSUE THREAD

**Issue by dbader** [TheRealJZ/slackernews#41]
Hi there,

I found slackernews incredibly useful and basically used it as my main way to catch up on Hacker News stories at least once a week. Now I'm getting this error message when I try to load up slackernews.io:

<img width="1276" alt="Screenshot 2019-04-29 16 40 43" src="https://user-images.githubusercontent.com/306708/56933623-8f69dc00-6a9d-11e9-9ce1-3f3f5aaad1a9.png">

Totally understand if you've moved on to other projects but I just wanted to say really enjoyed your site. Thank you! If there's some way I can help out by contributing to your hosting costs or something please let me know :)

Best,
Dan

**Comment by TheRealJZ** [comment]
Thanks for the kind words Dan!  I'm glad it's useful to you!
I haven't had a chance to look into what happened and fix, but plan to do so in the next week or so.  
Sorry for the disruption while I'm swamped!

**Comment by dbader** [comment]
Oh yeah no rush whatsoever! Thanks for running the site, it's awesome :)

**Comment by TheRealJZ** [comment]
Should be working now, thanks for the bug report and for using my site!
